const $ = (selector) => document.querySelector(selector);
let selected = 'year1';
const months = ['ינואר','פברואר','מרץ','אפריל','מאי','יוני','יולי','אוגוסט','ספטמבר','אוקטובר','נובמבר','דצמבר'];
function formatDate(value){const d=new Date(value+'T12:00:00');return {day:d.getDate(),month:months[d.getMonth()],full:d.toLocaleDateString('he-IL',{day:'2-digit',month:'2-digit',year:'numeric'})}}
function calendarLinks(event){const start=event.date.replaceAll('-','')+'T'+event.time.replace(':','')+'00';const end=event.date.replaceAll('-','')+'T'+event.end.replace(':','')+'00';const title=encodeURIComponent(event.title);const details=encodeURIComponent((event.note||'')+(event.zoom?'\nקישור Zoom: '+event.zoom:''));const location=encodeURIComponent(event.location+(event.zoom?' · '+event.zoom:''));return {google:`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${start}/${end}&details=${details}&location=${location}`,outlook:`https://outlook.live.com/calendar/0/deeplink/compose?subject=${title}&startdt=${event.date}T${event.time}:00&enddt=${event.date}T${event.end}:00&body=${details}&location=${location}`}}
function renderStations(){ $('#stations').innerHTML=schedule.stations.map((s,i)=>`<button class="station ${s.id===selected?'active':''}" data-id="${s.id}" aria-pressed="${s.id===selected}"><div class="station-dot">${s.icon}</div><h3>${s.title}</h3><p>${s.subtitle}</p></button>`).join('');document.querySelectorAll('.station').forEach(btn=>btn.addEventListener('click',()=>{selected=btn.dataset.id;render()}));$('#route-progress').style.width=((schedule.stations.findIndex(s=>s.id===selected)+1)/schedule.stations.length*100)+'%'}
function eventCard(e){const d=formatDate(e.date),links=calendarLinks(e);return `<article class="event-card"><div class="event-date"><b>${d.day}</b><small>${d.month}</small></div><div class="event-info"><h3>${e.title}</h3><p>${e.time}–${e.end} · ${e.location}</p><div class="tags"><span class="tag ${e.zoom?'zoom':'inperson'}">${e.zoom?'● Zoom':'● פרונטלי'}</span>${e.note?`<span class="tag">${e.note}</span>`:''}</div></div><div class="event-actions">${e.zoom?`<a href="${e.zoom}" target="_blank" rel="noopener">כניסה ל-Zoom</a>`:''}<a href="${links.google}" target="_blank" rel="noopener">Google Calendar</a><a href="${links.outlook}" target="_blank" rel="noopener">Outlook</a><a href="${e.feedback||'#'}" target="_blank" rel="noopener">משוב</a></div></article>`}
function deadlineCard(item,extra=''){const d=formatDate(item.date);return `<div class="deadline ${extra}"><div class="deadline-icon">${extra?'₪':'✓'}</div><div><time>${d.full}</time><h3>${item.title}</h3><p>${item.text}</p></div></div>`}
function render(){renderStations();const station=schedule.stations.find(s=>s.id===selected);const events=schedule.events.filter(e=>e.station===selected);$('#selected-title').textContent=`${station.title} · ${station.subtitle}`;$('#content').innerHTML=`<section class="panel events-panel"><div class="panel-heading"><h2>אירועים קרובים</h2><span class="count">${events.length} אירועים במסלול</span></div>${events.length?events.map(eventCard).join(''):'<p class="muted">עדיין לא נוספו אירועים. הצוות יוכל להוסיף אותם בקובץ data.js.</p>'}</section><aside><section class="panel"><div class="panel-heading"><h2>המחויבויות שלי</h2><span class="count">לפי מועדים</span></div>${schedule.deadlines.map(d=>deadlineCard(d)).join('')}</section><section class="panel scholarship"><div class="panel-heading"><h2>מועדי מלגות</h2><span class="count">תשפ״ז</span></div>${schedule.scholarships.map(d=>deadlineCard(d,'scholarship')).join('')}</section></aside>`}
$('#all-events').addEventListener('click',()=>{selected='all';renderStations();$('#selected-title').textContent='כל האירועים · תשפ״ז';const list=schedule.events.map(eventCard).join('');document.querySelector('.events-panel').innerHTML=`<div class="panel-heading"><h2>כל אירועי השנה</h2><span class="count">${schedule.events.length} אירועים</span></div>${list}`;document.querySelectorAll('.station').forEach(b=>b.classList.remove('active'))});$('#print-page').addEventListener('click',()=>window.print());render();
